image:
  registry: docker.io
  repository: mediawiki-install #heena29k/mediawiki-install
  tag: latest #v8
  pullPolicy: IfNotPresent

mediawikiUser: user
mediawikiDB: mediadb
mediawikiDBUser: heena
mediawikiDBPass: pass123

mediawikiEmail: user@example.com
mediawikiName: My Wiki
allowEmptyPassword: "yes"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 8Gi

ingress:
  enabled: false
  hosts:
  - name: mediawiki.local
    tls: false
    certManager: false
    tlsSecret: mediawiki.local-tls
    annotations:
